### ISSUE TITLE
ubuntu16启动时报错，但能启动网页开发

### ISSUE THREAD

**Issue by YanYuanFE** [yuan1994/wechat_web_devtools#18]
[如图](http://o9qn9041y.bkt.clouddn.com/%E9%80%89%E5%8C%BA_015.png)
终端输出如下：
 /opt/tencent/wechat_web_devtools/nw
[8255:8255:0215/102832:ERROR:desktop_window_tree_host_x11.cc(1131)] Not implemented reached in virtual void views::DesktopWindowTreeHostX11::InitModalType(ui::ModalType)
extensions::nw.App:66
    return nwNatives.getProxyForURL.apply(this, arguments);
                                    ^

Error: Invalid URL passed to App.getProxyForURL()
    at Object.<anonymous> (extensions::nw.App:66:37)
    at Object.handleRequest (extensions::binding:63:27)
    at Object.<anonymous> (extensions::binding:425:32)
    at Object.getProxyForURL (/opt/tencent/wechat_web_devtools/app/dist/utils/tools.js:1:2134)
    at b (/opt/tencent/wechat_web_devtools/app/dist/utils/checkUp.js:1:582)
    at c (/opt/tencent/wechat_web_devtools/app/dist/utils/checkUp.js:1:854)
    at e (/opt/tencent/wechat_web_devtools/app/dist/utils/checkUp.js:1:2190)
    at _exports (/opt/tencent/wechat_web_devtools/app/dist/utils/checkUp.js:1:3467)
    at b (/opt/tencent/wechat_web_devtools/app/dist/common/loadInit/init.js:1:971)
    at Request.g [as _callback] (/opt/tencent/wechat_web_devtools/app/dist/common/request/request.js:1:3024)

**Comment by levinit** [comment]
一样。启动报错，不过仍然可以打开。

**Comment by yuan1994** [comment]
版本已更新，我在ubuntu16.04上测试没有任何问题
