### ISSUE TITLE
Error: Invalid URL passed to App.getProxyForURL()

### ISSUE THREAD

**Issue by zhangfu-git** [yuan1994/wechat_web_devtools#19]
启动的时候弹窗：（无法加载以下来源的扩展程序：.清单文件缺失或不可读）
终端显示错误：
```javascript
extensions::nw.App:66
    return nwNatives.getProxyForURL.apply(this, arguments);
                                    ^

Error: Invalid URL passed to App.getProxyForURL()
    at Object.<anonymous> (extensions::nw.App:66:37)
    at Object.handleRequest (extensions::binding:63:27)
    at Object.<anonymous> (extensions::binding:425:32)
    at Object.getProxyForURL (/opt/tencent/wechat_web_devtools/app/dist/utils/tools.js:1:2134)
    at b (/opt/tencent/wechat_web_devtools/app/dist/utils/checkUp.js:1:582)
    at c (/opt/tencent/wechat_web_devtools/app/dist/utils/checkUp.js:1:854)
    at e (/opt/tencent/wechat_web_devtools/app/dist/utils/checkUp.js:1:2190)
    at _exports (/opt/tencent/wechat_web_devtools/app/dist/utils/checkUp.js:1:3467)
    at b (/opt/tencent/wechat_web_devtools/app/dist/common/loadInit/init.js:1:971)
    at Request.g [as _callback] (/opt/tencent/wechat_web_devtools/app/dist/common/request/request.js:1:3024)
```

**Comment by yuan1994** [comment]
已更新，感谢大家的支持，因做毕设忙得没心情更新了，耽误大家了，很抱歉

**Comment by Jihai-Tu** [comment]
这个是因为什么？清单文件缺失或不可读？
