### ISSUE TITLE
linux mint cinnamon 18 运行出错

### ISSUE THREAD

**Issue by jerry79** [yuan1994/wechat_web_devtools#2]
太感谢了，制作了这个工具。不然我还得在linxu和虚拟机之间来回切换。
linux mint cinnamon 18安装没有问题，终端运行有错误提示：
[21324:21324:1121/165043:ERROR:browser_plugin_guest.cc(440)] Attempting to require callback on nonexistent surface
界面无法加载预览页面，一直显示进度条，时间长了会提示错误，如图，请问这个大概是什么问题呢？谢谢！
![image](https://cloud.githubusercontent.com/assets/2713806/20476685/28a4cf2c-b00d-11e6-9013-8a0354931b0a.png)
![image](https://cloud.githubusercontent.com/assets/2713806/20476747/72f75018-b00d-11e6-92b4-fc7cb3702711.png)

**Comment by yuan1994** [comment]
mint没用过，你电脑上有没有安装 chrome 或者 chromium 浏览器，你安装浏览器后再试试？

**Comment by jerry79** [comment]
我的本来就装有chrome，我尝试卸载重装也不行。看问题应该是无法连接腾讯的服务器，这种可能是什么问题呢？我一开始以为是代理的问题，但是关掉代理也不行：（

**Comment by jerry79** [comment]
请问需要在电脑上安装nwjs开发环境吗？

**Comment by jerry79** [comment]
发现一个问题是，右侧列表显示是appservice.open.weixin.qq.com，但是网页提示是debug.open.weixin.qq.com无法连接，不知道这里有没有问题，唉，现在是有病乱球衣 ：（
![image](https://cloud.githubusercontent.com/assets/2713806/20509197/f72712d0-b0a1-11e6-9eeb-95253443cb44.png)

**Comment by yuan1994** [comment]
不需要安装nwjs环境，自带就有，不过建议你安装一下nodejs，你试一下你在你浏览器离能访问微信公众号平台，还有这个地址：https://open.weixin.qq.com/connect/qrconnect?appid=wxde40e023744664cb&redirect_uri=https%3a%2f%2fmp.weixin.qq.com%2fdebug%2fcgi-bin%2fwebdebugger%2fqrcode&scope=snsapi_login&state=login#wechat_redirect
然后试试能不能在开发者地址栏中输入然后访问这个地址

**Comment by yuan1994** [comment]
你可以尝试执行命令：sudo rm -rf ~/.config/微信web开发者工具/  和  sudo rm -rf ~/.cache/微信web开发者工具/

**Comment by jerry79** [comment]
都试了，搞不定，绝望了：（
微信今天更新了0.11版本，我下载下来，按照这个网页的方法，去尝试：
https://ruby-china.org/topics/30339
也不行，除了之前的那个错误，还有更多的错误出现
`[13505:13505:1122/130051:ERROR:browser_plugin_guest.cc(440)] Attempting to require callback on nonexistent surface
/home/jerry/nwjs-sdk-v0.18.7-linux-x64/app/dist/weapp/utils/parseErr.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";function init(){function r(r,e,t){for(var n=r.split("\n"),s=e-3>0?e-3:0,a=t?[t]:[],p=s;p<e;p++){var o=p===e-1?">":" ";a.push(o+" "+(p+1)+" | "+n[p])}return a}var e=require("path"),t=require("fs"),n=require("../../config/config.js"),s=require("../../lib/jsonlint.js").parser,a=require("../../stores/projectStores.js");s.parseError=s.lexer.parseError=function(r,e){throw e};var p=n.WXML_ERROR,o=n.WXML_LOSE_ERROR;_exports={},_exports.parseWXMLRuntimeErr=function(s){var p=a.getCurrentProject(),o=s.message.replace(n.WXML_RUNTIME_ERROR,""),i=o.split(":"),c=parseInt(i[2]);if(c!==-1){for(var l=t.readFileSync(e.join(p.projectpath,i[0]),"utf8"),u=o.replace(i[0]+":"+i[1]+":"+i[2]+":"+i[3]+":","").replace(/`/g,'"'),f=r(l,c,u),g="",j=0;j<i[3]-1;j++)g+=" ";f.push("  "+i[2].replace(/\d/g," ")+" | "+g+"^");var d={file:i[0],reason:u,msg:f.join("\n")};return d}},_exports.parseJsFil

Error: ENOENT: no such file or directory, open '/home/jerry/workspace/weixin/123456/run-detectors'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object._exports.parseWxmlErr (/home/jerry/nwjs-sdk-v0.18.7-linux-x64/app/dist/weapp/utils/parseErr.js:1:1889)
    at /home/jerry/nwjs-sdk-v0.18.7-linux-x64/app/dist/weapp/trans/transManager.js:1:1099
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at /home/jerry/nwjs-sdk-v0.18.7-linux-x64/app/dist/weapp/trans/transManager.js:1:1021
    at /home/jerry/nwjs-sdk-v0.18.7-linux-x64/node_modules/async/lib/async.js:251:17
    at done (/home/jerry/nwjs-sdk-v0.18.7-linux-x64/node_modules/async/lib/async.js:126:15)
    at /home/jerry/nwjs-sdk-v0.18.7-linux-x64/node_modules/async/lib/async.js:32:16
/home/jerry/nwjs-sdk-v0.18.7-linux-x64/app/dist/weapp/utils/parseErr.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";function init(){function r(r,e,t){for(var n=r.split("\n"),s=e-3>0?e-3:0,a=t?[t]:[],p=s;p<e;p++){var o=p===e-1?">":" ";a.push(o+" "+(p+1)+" | "+n[p])}return a}var e=require("path"),t=require("fs"),n=require("../../config/config.js"),s=require("../../lib/jsonlint.js").parser,a=require("../../stores/projectStores.js");s.parseError=s.lexer.parseError=function(r,e){throw e};var p=n.WXML_ERROR,o=n.WXML_LOSE_ERROR;_exports={},_exports.parseWXMLRuntimeErr=function(s){var p=a.getCurrentProject(),o=s.message.replace(n.WXML_RUNTIME_ERROR,""),i=o.split(":"),c=parseInt(i[2]);if(c!==-1){for(var l=t.readFileSync(e.join(p.projectpath,i[0]),"utf8"),u=o.replace(i[0]+":"+i[1]+":"+i[2]+":"+i[3]+":","").replace(/`/g,'"'),f=r(l,c,u),g="",j=0;j<i[3]-1;j++)g+=" ";f.push("  "+i[2].replace(/\d/g," ")+" | "+g+"^");var d={file:i[0],reason:u,msg:f.join("\n")};return d}},_exports.parseJsFil

Error: ENOENT: no such file or directory, open '/home/jerry/workspace/weixin/123456/run-detectors'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object._exports.parseWxmlErr (/home/jerry/nwjs-sdk-v0.18.7-linux-x64/app/dist/weapp/utils/parseErr.js:1:1889)
    at /home/jerry/nwjs-sdk-v0.18.7-linux-x64/app/dist/weapp/trans/transManager.js:1:1099
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at /home/jerry/nwjs-sdk-v0.18.7-linux-x64/app/dist/weapp/trans/transManager.js:1:1021
    at /home/jerry/nwjs-sdk-v0.18.7-linux-x64/node_modules/async/lib/async.js:251:17
    at done (/home/jerry/nwjs-sdk-v0.18.7-linux-x64/node_modules/async/lib/async.js:126:15)
    at /home/jerry/nwjs-sdk-v0.18.7-linux-x64/node_modules/async/lib/async.js:32:16
/home/jerry/nwjs-sdk-v0.18.7-linux-x64/app/dist/weapp/utils/parseErr.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";function init(){function r(r,e,t){for(var n=r.split("\n"),s=e-3>0?e-3:0,a=t?[t]:[],p=s;p<e;p++){var o=p===e-1?">":" ";a.push(o+" "+(p+1)+" | "+n[p])}return a}var e=require("path"),t=require("fs"),n=require("../../config/config.js"),s=require("../../lib/jsonlint.js").parser,a=require("../../stores/projectStores.js");s.parseError=s.lexer.parseError=function(r,e){throw e};var p=n.WXML_ERROR,o=n.WXML_LOSE_ERROR;_exports={},_exports.parseWXMLRuntimeErr=function(s){var p=a.getCurrentProject(),o=s.message.replace(n.WXML_RUNTIME_ERROR,""),i=o.split(":"),c=parseInt(i[2]);if(c!==-1){for(var l=t.readFileSync(e.join(p.projectpath,i[0]),"utf8"),u=o.replace(i[0]+":"+i[1]+":"+i[2]+":"+i[3]+":","").replace(/`/g,'"'),f=r(l,c,u),g="",j=0;j<i[3]-1;j++)g+=" ";f.push("  "+i[2].replace(/\d/g," ")+" | "+g+"^");var d={file:i[0],reason:u,msg:f.join("\n")};return d}},_exports.parseJsFil

Error: ENOENT: no such file or directory, open '/home/jerry/workspace/weixin/123456/run-detectors'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object._exports.parseWxmlErr (/home/jerry/nwjs-sdk-v0.18.7-linux-x64/app/dist/weapp/utils/parseErr.js:1:1889)
    at /home/jerry/nwjs-sdk-v0.18.7-linux-x64/app/dist/weapp/trans/transManager.js:1:1099
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at /home/jerry/nwjs-sdk-v0.18.7-linux-x64/app/dist/weapp/trans/transManager.js:1:1021
    at /home/jerry/nwjs-sdk-v0.18.7-linux-x64/node_modules/async/lib/async.js:251:17
    at done (/home/jerry/nwjs-sdk-v0.18.7-linux-x64/node_modules/async/lib/async.js:126:15)
    at /home/jerry/nwjs-sdk-v0.18.7-linux-x64/node_modules/async/lib/async.js:32:16

`

**Comment by yuan1994** [comment]
直接运行肯定更多的错误，，，不然我不会弄到 github 发布的，毕竟还是要折腾一点时间的

**Comment by jerry79** [comment]
能更新一下最新版试试吗？谢谢哈

**Comment by yuan1994** [comment]
嗯，今天下班回去就更新，今天才知道出新版的，肯定追着更新

**Comment by jerry79** [comment]
非常非常感谢！

**Comment by TroyWind** [comment]
同样的错误。请问大神有没有解决这个问题的办法呢。？

**Comment by TroyWind** [comment]
![wx_error](https://cloud.githubusercontent.com/assets/8196612/20708473/1227f42c-b66b-11e6-91b6-e27dd01506b6.png)
![wx_error2](https://cloud.githubusercontent.com/assets/8196612/20708477/16e866ea-b66b-11e6-9915-0a0c71a36367.png)

**Comment by jerry79** [comment]
@TroyWind 这个问题还没解决呢，唉，愁死了

**Comment by jerry79** [comment]
@TroyWind 你的也是mint 18？

**Comment by TroyWind** [comment]
@jerry79 不是，我是ubuntu 16.04.1 LTS。怎么我感觉微信是有意屏蔽linux的。他这东西打包个linux环境的安装包很容易的。

**Comment by jerry79** [comment]
@TroyWind 唉，其他人14.04运行没问题，mint 18是基于16.04的，看来是我们的版本太新了？？微信和QQ一样，dog sun tencent。

**Comment by duan602728596** [comment]
我是用nw.js运行的工具，然后在/home/用户名/.config/微信web开发者工具/WeappVendor内有两个文件wcc.exe，wcsc.exe，需要wine。如果我不提前运行这两个文件，就会报错，无法编译，提前在wine下运行这两个文件就会正常编译。或者将wcc.exe，wcsc.exe的.exe去掉，进入到package.nw/app/dist/weapp/文件夹，找到commit/build.js、trans/transWxmlToJs.js和utils/vendorManager.js，将代码中的wcc.exe和wcsc.exe改成wcc和wcsc，也可以正常编译不需要提前运行wcc.exe，wcsc.exel了。

run-detectors的问题好像是因为linux认为这个是文件夹，而不是文件，我的解决方法是在小程序的目录内提前建一个run-detectors文件。

**Comment by jerry79** [comment]
@duan602728596 谢谢，我按照你的方法试了，还是不行，无法编译

**Comment by jerry79** [comment]
按照duan602728596的方法运行成功，非常非常感谢。

**Comment by Heaven97** [comment]
我现在也是那个网页无法正常运作的错误，请问有什么办法解决？系统是ubuntu kylin16.04LTS的版本

**Comment by Heaven97** [comment]
@yuan1994

**Comment by RaydChang** [comment]
@jerry79 @duan602728596 能否看看我以下的问题:
我的还是没有办法正常模拟:
OS:Linux Mint 18.1 Serena (64-bit)
Chrome:56.0.2924.87 (64-bit)
用nwjs,做一些文件名调整后直接运行.
可以开启,但没模拟不正常,用官方的Sample,画面如下,没有出现Hello World.
(画面传不上来??)
到手机上预览正常.
弄了几天未果,希望得到您们的指点,万分感谢!!


LOG:
rayd@rayd-pc ~/applications/nwjs $ ./nw
[17416:17416:0407/162528.691351:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[17376:17376:0407/162531.001191:ERROR:CONSOLE(1)] "Uncaught ReferenceError: WebInspector is not defined", source:  (1)
[17376:17376:0407/162531.035823:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[17376:17376:0407/162535.230340:ERROR:CONSOLE(1)] "Uncaught ReferenceError: WebInspector is not defined", source:  (1)
[17376:17376:0407/162535.263392:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[17376:17376:0407/162538.833045:ERROR:CONSOLE(1)] "Uncaught ReferenceError: WebInspector is not defined", source:  (1)
[17376:17376:0407/162538.866197:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[17376:17376:0407/162715.891726:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[17376:17376:0407/162715.953146:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[17376:17376:0407/162716.010405:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[17376:17376:0407/162716.055670:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[17376:17376:0407/162716.466366:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[17376:17376:0407/162716.540700:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[17376:17376:0407/162716.791810:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[17376:17376:0407/162717.108774:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[17376:17376:0407/162717.650721:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[17376:17376:0407/162718.573263:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[17376:17376:0407/162719.917950:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[17376:17376:0407/162721.260417:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[17376:17376:0407/162722.493576:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[17416:17416:0407/163530.627448:ERROR:interface_registry.cc(203)] Failed to locate a binder for interface: chrome::mojom::ResourceUsageReporter requested by:  exposed by:  via InterfaceProviderSpec "service_manager:connector".

**Comment by RaydChang** [comment]
以上问题已经通过摸索已经解决，参考
https://my.oschina.net/raydchang/blog/875187
主要是目录路径问题，不要留用package.nw目录
还是要感谢@jerry79 @duan602728596
是在他们提供的思路上解决自己的问题，谢谢！

**Comment by yuan1994** [comment]
已更新，感谢大家的支持，因做毕设忙得没心情更新了，耽误大家了，很抱歉
