### ISSUE TITLE
Cannot find module 'async'

### ISSUE THREAD

**Issue by SharksevenRo** [yuan1994/wechat_web_devtools#25]
ubuntu

Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:479:15)
    at Function.Module._load (module.js:422:25)
    at Module.require (module.js:507:17)
    at require (internal/module.js:20:19)
    at init (/home/sharkseven/installer/wechat_web_devtools/app/dist/common/request/request.js:1:3133)
    at Object.<anonymous> (/home/sharkseven/installer/wechat_web_devtools/app/dist/common/request/request.js:1:3433)
    at Module._compile (module.js:580:32)
    at Object.Module._extensions..js (module.js:595:10)
    at Module.load (module.js:497:32)
    at tryModuleLoad (module.js:456:12)

**Comment by SharksevenRo** [comment]
npm install async --save
就可以了

**Comment by yuan1994** [comment]
这个问题很奇怪，我本地也发现过此问题，然后覆盖文件后正常了，之后再想提交git，结果显示没有文件改动，从 oss 下载的安装包也没有任何问题
